pages/urls.py
from django.urls import path
from .views import HomeView, AboutView, contact, ExperienceView
urlpatterns = [
	path('', HomeView.as_view(), name='home'),
	path('about/', AboutView.as_view(), name='about'),
	path('contact/', contact, name='contact'),
	path('exp/', ExperienceView.as_view(), name ='exp'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'SK Portfolio Admin'
admin.site.index_title = 'SK Portfolio Administration'
admin.site.site_title = 'SK Portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('projects/', include('projects.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from .views import ProjectDetailView
urlpatterns = [
	path('<int:pk>/',ProjectDetailView.as_view(), name='detail'),
]

pages/models.py
from django.db import models

# Create your models here.
class AboutDescription(models.Model):
	content = models.TextField()
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


class ContactDescription(models.Model):
	content = models.TextField()
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

class Experience(models.Model):
	content = models.TextField()
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	class Meta:
		ordering = ['-timestamp']

projects/models.py
from django.db import models
from django.urls import reverse
from PIL import Image
from markdown_deux import markdown
from django.utils.safestring import mark_safe

def upload_location(instance, filename):
	print(instance)
	return "projects/{}".format(filename)



class Project(models.Model):
	title = models.CharField(max_length = 200)
	thum = models.ImageField(upload_to=upload_location)
	description = models.CharField(max_length=200, null = True, blank = True)
	content = models.TextField()
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	classes = models.CharField(max_length=200, null=True, blank = True)
	def __str__(self):
		return str(self.title)
	
	def get_absolute_url(self):
		return reverse('detail', kwargs={'pk': self.pk})
	
	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

	# def save(self, *args, **kwargs):
	# 	super().save(*args, **kwargs)
	# 	img = Image.open(self.thum.path)
	# 	img = img.resize((600, 400))
	# 	img.save(self.thum.path)

class Images(models.Model):
	project = models.ForeignKey(Project, on_delete= models.CASCADE)
	image = models.ImageField(upload_to=upload_location, null=True, blank=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.image.name

	# def save(self, *args, **kwargs):
	# 	super().save(*args, **kwargs)
	# 	img = Image.open(self.image.path)
	# 	img = img.resize((900, 400))
	# 	img.save(self.image.path)

pages/forms.py
from django import forms
from projects.models import Project

class ContactForm(forms.Form):
	name = forms.CharField(max_length=200, required=True)
	email = forms.EmailField(max_length=200, required=True)
	content = forms.CharField(required=True,widget=forms.Textarea, label='Message')

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from projects.views import Project
from .models import AboutDescription, ContactDescription,Experience
from .forms import ContactForm
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.contrib import messages
from django.shortcuts import redirect
class HomeView(ListView):
	model = Project
	context_object_name = 'projects'
	template_name = 'home.html'

class AboutView(TemplateView):
	template_name = 'about.html'
	context_object_name = 'about'
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['about'] = AboutDescription.objects.latest('timestamp')
		return context

class ExperienceView(TemplateView):
	template_name = 'experience.html'
	context_object_name = 'experience'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['experiences'] = Experience.objects.all()
		return context

def contact(request):
	form_class = ContactForm
	if request.method == 'POST':
		form = form_class(data=request.POST)
		if form.is_valid():
			contact_name = request.POST['name']
			contact_email = request.POST['email']
			content = request.POST['content']

			template = get_template('contact_template.txt')
			context = {
				'contact_name': contact_name,
				'contact_email': contact_email,
				'form_content':content
			}
			content = template.render(context)
			email = EmailMessage("New Email from portfolio", content, 'Shubham-Portfolio', ['shubhamkumar7051@gmail.com'], headers={'Reply-To': contact_email})
			email.send()
			messages.success(request,'Thanks for getting in touch.')
			return redirect('contact')
		else:
			messages.error(request, 'Unable to send email make sure all the fields are correct')
			return redirect('contact')
	context = {
		'contact': ContactDescription.objects.latest('timestamp'),
		}
	return render(request,'contact.html',context=context)
	

projects/views.py
from django.shortcuts import render

from django.views.generic import DetailView
from .models import Project
class ProjectDetailView(DetailView):
	model = Project
	context_object_name = 'project'
	template_name = 'projects/detail.html'

templates/about.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% block title %}
Shubham-About
{% endblock title %}

{% block content %}
<div class="text-content">
	<div class="content-column-content">
	  {{ about.content | markdown | linebreaks }}
	</div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %} Shubham {% endblock title %}</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="all,follow">
	
	<script src="https://kit.fontawesome.com/298352837c.js" crossorigin="anonymous"></script>

	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
	
	<!-- Custom stylesheet - for your changes-->
	<link rel="stylesheet" href="{% static 'css/custom.css' %}" >
</head>
<style>

</style>
<body>
	<div class="all">
		<div class="sidebar" id="sidebar">
			<div class="profile">
				<a class="profile-name-link" href="/"><h3>SHUBHAM KUMAR</h3></a>
				<p class="profile-bio">
					I am a computer science student and a fullstack web devloper,
					Currently working as an intern in a startup.
					<p>Always Learning,Developing or solving.</p>
				</p>
			</div>
			<div class="sidebar-links">
				<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
				<a href="{% url 'home' %}" class="sidebar-link" id="home">Portfolio</a>
				<a href="{% url 'about' %}" class="sidebar-link" id="about">About</a>
				<a href="{% url 'contact' %}" class="sidebar-link" id="contact">Get in Touch</a>
				<a href="{% url 'exp' %}" class="sidebar-link" id="exp">Experience</a>
			</div>
			<div class="contact-links">
				<a href="https://github.com/shubhamsks" target="_blank"><i class="fa fa-github"></i></a>
				<a href="https://linkedin.com/in/shubham--sk" target="_blank"><i class="fa fa-linkedin"></i></a>
				<a href="https://twitter.com/shubham__sks" target="_blank"><i class="fa fa-twitter"></i></a>
			</div>
		</div>
		<div class="portfolio">
			<div class="top-bar">
				<button id="menu-btn" class="menu">
					<div class="one"></div>
					<div class="two"></div>
					<div class="three"></div>
				</button>
				<div class="name-heading">
					<h2>
						Shubham Kumar
					</h2>
				</div>
			</div>
			<div class="navbar" id='filters'>
				<button id="all-filter" class="badge active">All</button>
				<button id="django-filter" class="badge">Django</button>
				<button id="react-filter" class="badge">React</button>
				<button id="android-filter" class="badge">Android</button>
				<button id="ai-filter" class="badge">AI/ML</button>
			</div>
			<div class="container">
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-{{message.tags}}">
							<span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
							{{ message}}
						</div>
					{% endfor %}
				{% endif %}
				{% block content %}

				{% endblock content%}
			</div>
		</div>
	</div>

	{% block javascript %}
	<script src="{% static 'js/front.js' %}"></script>
	<script src="{% static 'js/base.js' %}"></script>
	{% endblock javascript %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% load crispy_forms_tags %}
{% block title %}
Shubham-About
{% endblock title %}

{% block content %}
<style>
form {
	max-width: 300px;
	margin: 10px auto;
	padding: 20px 20px 20px 20px;	
	padding-right: 50px;
	background: #f4f7f8;
	border-radius: 8px;
}

h1 {
  margin: 0 0 30px 0;
  text-align: center;
}

input[type="text"],
input[type="password"],
input[type="date"],
input[type="datetime"],
input[type="email"],
input[type="number"],
input[type="search"],
input[type="tel"],
input[type="time"],
input[type="url"],
textarea,
select {
  background: rgba(255, 255, 255, 0.1);
  border: none;
  font-size: 16px;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 15px;
  width: 100%;
  background-color: #e8eeef;
  color: #8a97a0;
  box-shadow: 0 1px 0 rgba(0, 0, 0, 0.03) inset;
  margin-bottom: 30px;
}

input[type="radio"],
input[type="checkbox"] {
  margin: 0 4px 8px 0;
}

select {
  padding: 6px;
  height: 32px;
  border-radius: 2px;
}

.form-submit-btn {
  cursor: pointer;
  padding: 19px 39px 18px 39px;
  color: #FFF;
  background-color:#50507F;
  font-size: 18px;
  text-align: center;
  font-style: normal;
  border-radius: 5px;
  width: 100%;
  border: 1px solid #50507F;
  border-width: 1px 1px 3px;
  box-shadow: 0 -1px 0 rgba(255, 255, 255, 0.1) inset;
  margin-bottom: 10px;
}
.form-submit-btn:active{
  transform: scale(1.02);
}
fieldset {
  margin-bottom: 30px;
  border: none;
}

legend {
  font-size: 1.4em;
  margin-bottom: 10px;
}

label {
  display: block;
  margin-bottom: 8px;
}

label.light {
  font-weight: 300;
  display: inline;
}

.number {
  background-color: #5fcf80;
  color: #fff;
  height: 30px;
  width: 30px;
  display: inline-block;
  font-size: 0.8em;
  margin-right: 4px;
  line-height: 30px;
  text-align: center;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.2);
  border-radius: 100%;
}

@media screen and (min-width: 480px) {
  form {
    max-width: 480px;
  }
}
</style>
		{{ contact.content | markdown | linebreaks }}
		<form method="POST">
			
			{% csrf_token %}	
			<fieldset>
			  <legend>Your basic info</legend>
			  <label for="name">Name:</label>
			  <input type="text" id="name" name="name" required>
		  
			  <label for="mail">Email:</label>
			  <input type="email" id="mail" name="email" required>
		  
			  <label for="content">Your message</label>
			  <textarea id="content" name="content" required rows="15"></textarea>
			  
			</fieldset>

			<button type="submit" class="form-submit-btn">Send Message</button>
		</form>
{% endblock content %}

templates/experience.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}
{% block title %}
Shubham-Experience
{% endblock title %}

{% block content %}
<div class="text-content">
	<div>
	  {% for experience in experiences %}
	  <div>
		  {{ experience.content | markdown | linebreaks}}
	  </div>
	  <hr>
	  {% endfor %}
	</div>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %} Shubham-Home {% endblock title %}


{% block content %}
<div class="portfolio-projects">
	{% for project in projects %}
	<div class="project card {% if project.classes %} {{ project.classes}} {% endif %}"> 
		<a href="{{ project.get_absolute_url }}">
			<div class="image">
			<img src="{{ project.thum.url }}">
			</div>
		</a>
		<div class="project-text"> 
			<h4> <a class="project-link"  href="{{ project.get_absolute_url }}">{{ project.title }} </a></h4>
			
			<div class="project-description">
				<p>{{ project.description }} </p>
			</div>
		</div>
	</div>
	{% endfor %}
{% endblock content %}
	
</div>	

templates/projects/detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_deux_tags %}
{% block title %} Project - {{ project.title }} {% endblock title %}
<style>
	*{
		visibility: visible;
	}
</style>
{% block content %}
<div class="text-content">
	<div class="content-column-content">
	  <h1>{{ project.title }}</h1>
	  <p class="lead">{{ project.description }}</p>
	  <div id="img-slider">
		{% for img in project.images_set.all %}
		<div class="slide fade">
			<img src="{{ img.image.url }}" alt="" class="img-fluid">
		</div>
		{% endfor %}
		<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
		<a class="next" onclick="plusSlides(1)">&#10095;</a>
	  </div>
	 <div>
		 {{ project.content | markdown | linebreaks}}
	 </div>
	</div>
</div>
{% endblock content %}